project:
  type: website
  output-dir: docs

website:
  title: "ling343-winter2024-classroom.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: quartz
      dark: darkly
    css: styles.css
    toc: true



